#ZeldaRPG Save File
#Mon Jun 29 13:10:59 IST 2026
potionCount=1
level=2
inventory=Shield,Potion,Shield,Sword
gold=146
attackDamage=28
hasWeapon=true
xpToLevel=140
xp=95
defense=10
currentZone=Great Savannah
playTimeTicks=9967
maxLife=115
quests=Q_SLIMES\:COMPLETED\:5\:false;Q_FOREST\:COMPLETED\:0\:true;Q_SKELETONS\:COMPLETED\:3\:false;Q_CAVES\:ACTIVE\:0\:false;Q_SAVANNAH\:COMPLETED\:0\:true;
life=82
hasShield=true
worldY=1183
worldX=1049
