#ZeldaRPG Save File
#Fri Oct 09 02:16:14 IST 2026
potionCount=24
level=9
inventory=Shield,Potion,Shield,Sword,Potion,Potion,Shield,Potion,Potion,Potion,Potion,Potion,Potion,Potion,Potion,Potion,Potion,Potion,Potion,Sword,Potion,Potion,Potion,Potion,Potion,Potion,Potion
gold=413
attackDamage=64
hasWeapon=true
xpToLevel=1470
xp=261
defense=15
currentZone=Dusty Gulch
playTimeTicks=95672
maxLife=220
quests=Q_SLIMES\:COMPLETED\:5\:false;Q_FOREST\:COMPLETED\:0\:true;Q_SKELETONS\:COMPLETED\:3\:false;Q_CAVES\:COMPLETED\:0\:true;Q_SAVANNAH\:COMPLETED\:0\:true;Q_OUTLAWS\:INACTIVE\:0\:false;
life=220
hasShield=true
worldY=489
worldX=4482
