#ZeldaRPG Save File
#Fri Oct 09 01:38:57 IST 2026
potionCount=17
level=8
inventory=Shield,Potion,Shield,Sword,Potion,Potion,Shield,Potion,Potion,Potion,Potion,Potion,Potion,Potion,Potion,Potion,Potion,Potion,Potion,Sword,Potion,Potion
gold=2063
attackDamage=61
hasWeapon=true
xpToLevel=1050
xp=726
defense=15
currentZone=Darkwood Forest
playTimeTicks=79907
maxLife=205
quests=Q_SLIMES\:COMPLETED\:5\:false;Q_FOREST\:COMPLETED\:0\:true;Q_SKELETONS\:COMPLETED\:3\:false;Q_CAVES\:COMPLETED\:0\:true;Q_SAVANNAH\:COMPLETED\:0\:true;Q_OUTLAWS\:INACTIVE\:0\:false;
life=191
hasShield=true
worldY=1864
worldX=2110
