#ZeldaRPG Save File
#Mon Jun 29 21:21:09 IST 2026
potionCount=5
level=5
inventory=Shield,Potion,Shield,Sword,Potion,Potion,Shield,Potion,Potion
gold=696
attackDamage=37
hasWeapon=true
xpToLevel=383
xp=185
defense=15
currentZone=Great Savannah
playTimeTicks=27386
maxLife=160
quests=Q_SLIMES\:COMPLETED\:5\:false;Q_FOREST\:COMPLETED\:0\:true;Q_SKELETONS\:COMPLETED\:3\:false;Q_CAVES\:COMPLETED\:0\:true;Q_SAVANNAH\:COMPLETED\:0\:true;
life=160
hasShield=true
worldY=1124
worldX=1886
